dist: xenial
language: node_js
node_js: [node]
cache: yarn
script: [yarn test, yarn ci-lint]
before_deploy: yarn version --no-git-tag-version --new-version "$TRAVIS_TAG"
deploy:
  provider: npm
  skip_cleanup: true
  email: ezzatron+iconduit@gmail.com
  api_key:
    secure: "U8Qx/2ylxT25xwLjnmwr9itRO7lzwqoCx9gDtIzo0p384WkE80ccUrVdpYGdnTgnp4W4gIcTiCVkyWlHDFfnIDU5D8zpPvKeoL2yF7CqCdIoLfpoG+e8VzUI56EnzDfDnY3xz9MMNTaiSpraCvl4t7+8E6WjzmEwJus/on7KrBplXL1tUcK1W8or6KYNGAmJrj5Sn/jyT6MtsSK3gsWcTWmVXuy0payLmaYCc2BCtIEdLygKolFxh9ui4v1Jjfgj53DnKu60DVIsw5IpSF8/Xblb2GcPex2kNbcvI44k5+ikF7C9E1thZxTRAoPP4JapQGmwsWJpckULQPo6Pb6+1P8qzgoWjU+t5t0Gp1FqvJAsQjoT42CcC0pID2JholunQ3rhYUPqkorv3L1PJ7PcdNIFQXhb0IGrw4RfAidEiBRMjvR8Zx0Af1YZhja5yevDXXDreFSq6sI/jFmKza7evDjDcQjESfb6/n0YSFoAfEj3psQWbQupzcySVZE1w2ES+6rsZzUfvJNhY8s1QAg1MEMXsjoR1uzoYJx0uzH5tLuiNbQ3EPsHLHeZpwk4bFiY9HeiBDjFxwy3aCqn0vH8SXRqZI4D9sAvhWpz8jVvg9SFO5qdxL9lcQ8LY+URlMrdG69ILvk/RjWlIbdBirIFX32nz6YiBSDt99B7lFS7H44="
  on:
    tags: true
